name: Foundry Test
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v4
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-lock: ./contracts/Scarb.lock
      - name: Run snforge test in contracts
        working-directory: contracts
        run: snforge test